# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convert2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(431, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #22222e")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 431, 270))
        self.frame.setStyleSheet("background-color: #fb5b5d")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(150, 10, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.Convert = QtWidgets.QPushButton(self.frame)
        self.Convert.setGeometry(QtCore.QRect(170, 190, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        self.Convert.setFont(font)
        self.Convert.setStyleSheet("QPushButton {\n"
"background-color: #FF5733;\n"
"border-radius: 30;\n"
"color: white;\n"
"border-color: #FF5733;\n"
"}\n"
"QPushButton: pressed {\n"
"background-color: #fa4244;\n"
"}")
        self.Convert.setObjectName("Convert")
        self.inputSum = QtWidgets.QLineEdit(self.centralwidget)
        self.inputSum.setGeometry(QtCore.QRect(20, 360, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        self.inputSum.setFont(font)
        self.inputSum.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white;")
        self.inputSum.setAlignment(QtCore.Qt.AlignCenter)
        self.inputSum.setObjectName("inputSum")
        self.inputCur = QtWidgets.QLineEdit(self.centralwidget)
        self.inputCur.setGeometry(QtCore.QRect(20, 290, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        self.inputCur.setFont(font)
        self.inputCur.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white;")
        self.inputCur.setAlignment(QtCore.Qt.AlignCenter)
        self.inputCur.setObjectName("inputCur")
        self.outputCur = QtWidgets.QLineEdit(self.centralwidget)
        self.outputCur.setGeometry(QtCore.QRect(20, 430, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        self.outputCur.setFont(font)
        self.outputCur.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white;")
        self.outputCur.setAlignment(QtCore.Qt.AlignCenter)
        self.outputCur.setObjectName("outputCur")
        self.outputSum = QtWidgets.QLineEdit(self.centralwidget)
        self.outputSum.setGeometry(QtCore.QRect(20, 500, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        self.outputSum.setFont(font)
        self.outputSum.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white;")
        self.outputSum.setAlignment(QtCore.Qt.AlignCenter)
        self.outputSum.setObjectName("outputSum")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CONVERTER"))
        self.Convert.setText(_translate("MainWindow", "CONVERT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
